<?php
/**
 * Created by PhpStorm.
 * User: PCink
 * Date: 2018/08/28
 * Time: 22:54
 */

namespace Core\Discord\Threads;


use pocketmine\Thread;

class SendMessage extends Thread
{
	public function __construct()
	{
	}

	public function run()
	{
		parent::run(); // TODO: Change the autogenerated stub
	}
}